"""initial

Revision ID: e7d93fe89862
Revises: 
Create Date: 2026-03-15 23:34:55.160651
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7d93fe89862'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
